### ISSUE TITLE
randomly stops

### ISSUE THREAD

**Issue by ewof** [Winds-Studio/Folia-Expansion#2]
it will just randomly break
i use the folia tps in the tab and it works but then after some time it just displays %folia_tps_5s_colored% and i have to do /tab reload

**Comment by 0x15d2** [comment]
same

**Comment by 0x15d2** [comment]
11.10.2024 - 00:18:18 - java.lang.NullPointerException: Cannot invoke "io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.getData()" because "currentRegion" is null
11.10.2024 - 00:18:18 - 	at org.dreeam.expansion.folia.FoliaUtils.getTPS(FoliaUtils.java:94)
11.10.2024 - 00:18:18 - 	at org.dreeam.expansion.folia.FoliaExpansion.getFoliaTPS(FoliaExpansion.java:237)
11.10.2024 - 00:18:18 - 	at org.dreeam.expansion.folia.FoliaExpansion.onRequest(FoliaExpansion.java:149)
11.10.2024 - 00:18:18 - 	at PlaceholderAPI-2.11.7-DEV-Folia.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
11.10.2024 - 00:18:18 - 	at PlaceholderAPI-2.11.7-DEV-Folia.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
11.10.2024 - 00:18:18 - 	at PlaceholderAPI-2.11.7-DEV-Folia.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
11.10.2024 - 00:18:18 - 	at TAB.v4.1.8.jar//me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$7(BukkitPlatform.java:194)
11.10.2024 - 00:18:18 - 	at TAB.v4.1.8.jar//me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:118)
11.10.2024 - 00:18:18 - 	at TAB.v4.1.8.jar//me.neznamy.tab.shared.placeholders.PlaceholderRefreshTask.run(PlaceholderRefreshTask.java:58)
11.10.2024 - 00:18:18 - 	at TAB.v4.1.8.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.lambda$refresh$1(PlaceholderManagerImpl.java:84)
11.10.2024 - 00:18:18 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
11.10.2024 - 00:18:18 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
11.10.2024 - 00:18:18 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
11.10.2024 - 00:18:18 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
11.10.2024 - 00:18:18 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
11.10.2024 - 00:18:18 - 	at java.base/java.lang.Thread.run(Thread.java:1583)


this might be the issue? cuz when i do /tab reload in game it returns the right tps amount for my region but when i do /tab reload on the console it just returns %folia_tps_5s_colored%

**Comment by 0x15d2** [comment]
yeah thats the issue you can use %folia_global_tps_5s_colored% or you can make your own plugin that reloads tablist for each player

**Comment by Valeqs** [comment]
> it will just randomly break i use the folia tps in the tab and it works but then after some time it just displays %folia_tps_5s_colored% and i have to do /tab reload



> 11.10.2024 - 00:18:18 - java.lang.NullPointerException: Cannot invoke "io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.getData()" because "currentRegion" is null 11.10.2024 - 00:18:18 - at org.dreeam.expansion.folia.FoliaUtils.getTPS(FoliaUtils.java:94) 11.10.2024 - 00:18:18 - at org.dreeam.expansion.folia.FoliaExpansion.getFoliaTPS(FoliaExpansion.java:237) 11.10.2024 - 00:18:18 - at org.dreeam.expansion.folia.FoliaExpansion.onRequest(FoliaExpansion.java:149) 11.10.2024 - 00:18:18 - at PlaceholderAPI-2.11.7-DEV-Folia.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) 11.10.2024 - 00:18:18 - at PlaceholderAPI-2.11.7-DEV-Folia.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) 11.10.2024 - 00:18:18 - at PlaceholderAPI-2.11.7-DEV-Folia.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) 11.10.2024 - 00:18:18 - at TAB.v4.1.8.jar//me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$7(BukkitPlatform.java:194) 11.10.2024 - 00:18:18 - at TAB.v4.1.8.jar//me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:118) 11.10.2024 - 00:18:18 - at TAB.v4.1.8.jar//me.neznamy.tab.shared.placeholders.PlaceholderRefreshTask.run(PlaceholderRefreshTask.java:58) 11.10.2024 - 00:18:18 - at TAB.v4.1.8.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.lambda$refresh$1(PlaceholderManagerImpl.java:84) 11.10.2024 - 00:18:18 - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) 11.10.2024 - 00:18:18 - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) 11.10.2024 - 00:18:18 - at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) 11.10.2024 - 00:18:18 - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) 11.10.2024 - 00:18:18 - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) 11.10.2024 - 00:18:18 - at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> this might be the issue? cuz when i do /tab reload in game it returns the right tps amount for my region but when i do /tab reload on the console it just returns %folia_tps_5s_colored%

**I just did a rework on the code and it works now.

use this code for the FoliaExpansion.class**

package org.dreeam.expansion.folia;

import io.papermc.paper.threadedregions.RegionizedServer;
import io.papermc.paper.threadedregions.ThreadedRegionizer;
import io.papermc.paper.threadedregions.TickData;
import io.papermc.paper.threadedregions.TickRegionScheduler;
import io.papermc.paper.threadedregions.TickRegions;
import net.minecraft.world.level.Level;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class FoliaUtils {

    public boolean isFolia = false;

    public void checkFolia() {
        try {
            Class.forName("io.papermc.paper.threadedregions.RegionizedServer");
            isFolia = true;
        } catch (ClassNotFoundException e) {
            isFolia = false;
        }
    }

    public List<Double> getGlobalTPS() {
        final TickRegionScheduler.RegionScheduleHandle regionHandle = RegionizedServer.getGlobalTickData();
        double tps_5s = regionHandle.getTickReport5s(System.nanoTime()).tpsData().segmentAll().average();
        double tps_15s = regionHandle.getTickReport15s(System.nanoTime()).tpsData().segmentAll().average();
        double tps_1m = regionHandle.getTickReport1m(System.nanoTime()).tpsData().segmentAll().average();
        double tps_5m = regionHandle.getTickReport5m(System.nanoTime()).tpsData().segmentAll().average();
        double tps_15m = regionHandle.getTickReport15m(System.nanoTime()).tpsData().segmentAll().average();
        return List.of(tps_5s, tps_15s, tps_1m, tps_5m, tps_15m);
    }

    public List<Double> getGlobalMSPT() {
        final TickRegionScheduler.RegionScheduleHandle regionHandle = RegionizedServer.getGlobalTickData();
        double mspt_5s = regionHandle.getTickReport5s(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        double mspt_15s = regionHandle.getTickReport15s(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        double mspt_1m = regionHandle.getTickReport1m(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        double mspt_5m = regionHandle.getTickReport5m(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        double mspt_15m = regionHandle.getTickReport15m(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        return List.of(mspt_5s, mspt_15s, mspt_1m, mspt_5m, mspt_15m);
    }

    public double getGlobalUtil() {
        final List<ThreadedRegionizer.ThreadedRegion<TickRegions.TickRegionData, TickRegions.TickRegionSectionData>> regions = new ArrayList<>();
        for (final World bukkitWorld : Bukkit.getWorlds()) {
            ((Level) bukkitWorld).getWorld().getHandle().regioniser.computeForAllRegions(regions::add);
        }
        double totalUtil = 0.0;
        final long now = System.nanoTime();
        final TickRegionScheduler.RegionScheduleHandle regionHandle = RegionizedServer.getGlobalTickData();
        for (final ThreadedRegionizer.ThreadedRegion<TickRegions.TickRegionData, TickRegions.TickRegionSectionData> region : regions) {
            final TickData.TickReportData report = region.getData().getRegionSchedulingHandle().getTickReport15s(now);
            totalUtil += (report == null ? 0.0 : report.utilisation());
        }
        totalUtil += regionHandle.getTickReport15s(now).utilisation();
        return totalUtil;
    }

    public List<Double> getTPS(Location location) {
        World world = location.getWorld();
        ThreadedRegionizer.ThreadedRegion<TickRegions.TickRegionData, TickRegions.TickRegionSectionData> currentRegion = TickRegionScheduler.getCurrentRegion();
        if (currentRegion == null || currentRegion.getData() == null) {
            return getGlobalTPS();
        }
        final TickRegionScheduler.RegionScheduleHandle regionHandle = currentRegion.getData().getRegionSchedulingHandle();
        double tps_5s = regionHandle.getTickReport5s(System.nanoTime()).tpsData().segmentAll().average();
        double tps_15s = regionHandle.getTickReport15s(System.nanoTime()).tpsData().segmentAll().average();
        double tps_1m = regionHandle.getTickReport1m(System.nanoTime()).tpsData().segmentAll().average();
        double tps_5m = regionHandle.getTickReport5m(System.nanoTime()).tpsData().segmentAll().average();
        double tps_15m = regionHandle.getTickReport15m(System.nanoTime()).tpsData().segmentAll().average();
        return List.of(tps_5s, tps_15s, tps_1m, tps_5m, tps_15m);
    }

    public List<Double> getMSPT(Location location) {
        World world = location.getWorld();
        ThreadedRegionizer.ThreadedRegion<TickRegions.TickRegionData, TickRegions.TickRegionSectionData> currentRegion = TickRegionScheduler.getCurrentRegion();
        if (currentRegion == null || currentRegion.getData() == null) {
            return getGlobalMSPT();
        }
        final TickRegionScheduler.RegionScheduleHandle regionHandle = currentRegion.getData().getRegionSchedulingHandle();
        double mspt_5s = regionHandle.getTickReport5s(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        double mspt_15s = regionHandle.getTickReport15s(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        double mspt_1m = regionHandle.getTickReport1m(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        double mspt_5m = regionHandle.getTickReport5m(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        double mspt_15m = regionHandle.getTickReport15m(System.nanoTime()).timePerTickData().segmentAll().average() / 1.0E6;
        return List.of(mspt_5s, mspt_15s, mspt_1m, mspt_5m, mspt_15m);
    }

    public List<Double> getUtil(Location location) {
        if (location == null) {
            return Collections.singletonList(getGlobalUtil());
        }
        World world = location.getWorld();
        if (world == null) {
            return Collections.singletonList(getGlobalUtil());
        }
        ThreadedRegionizer.ThreadedRegion<TickRegions.TickRegionData, TickRegions.TickRegionSectionData> currentRegion = TickRegionScheduler.getCurrentRegion();
        if (currentRegion == null || currentRegion.getData() == null) {
            return Collections.singletonList(getGlobalUtil());
        }
        final TickRegionScheduler.RegionScheduleHandle regionHandle = currentRegion.getData().getRegionSchedulingHandle();
        double util_5s = regionHandle.getTickReport5s(System.nanoTime()).utilisation();
        double util_15s = regionHandle.getTickReport15s(System.nanoTime()).utilisation();
        double util_1m = regionHandle.getTickReport1m(System.nanoTime()).utilisation();
        double util_5m = regionHandle.getTickReport5m(System.nanoTime()).utilisation();
        double util_15m = regionHandle.getTickReport15m(System.nanoTime()).utilisation();
        return List.of(util_5s, util_15s, util_1m, util_5m, util_15m);
    }

    public double maxThreadsCount() {
        return TickRegions.getScheduler().getTotalThreadCount();
    }
}

**Comment by Valeqs** [comment]
> it will just randomly break i use the folia tps in the tab and it works but then after some time it just displays %folia_tps_5s_colored% and i have to do /tab reload



> same

I fixed it. Replace this FoliaUtils.java with this code.

[replace_FoliaUtilsdotjava_with_this.txt](https://github.com/user-attachments/files/20107383/replace_FoliaUtilsdotjava_with_this.txt)

**Comment by ewof** [comment]
u should make a pr

**Comment by Valeqs** [comment]
> u should make a pr



> yeah thats the issue you can use %folia_global_tps_5s_colored% or you can make your own plugin that reloads tablist for each player

fixed it

https://github.com/Valeqs/Folia-Expansion-Tab-Fix
